//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about_24 {
            get {
                object obj = ResourceManager.GetObject("about_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap activate_pro_16 {
            get {
                object obj = ResourceManager.GetObject("activate_pro_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap activate_pro_16__2_ {
            get {
                object obj = ResourceManager.GetObject("activate_pro_16__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap activate_pro_48 {
            get {
                object obj = ResourceManager.GetObject("activate_pro_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_16 {
            get {
                object obj = ResourceManager.GetObject("add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_16_pale {
            get {
                object obj = ResourceManager.GetObject("add_16_pale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon app {
            get {
                object obj = ResourceManager.GetObject("app", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap apps_16 {
            get {
                object obj = ResourceManager.GetObject("apps_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aspdotnet_48 {
            get {
                object obj = ResourceManager.GetObject("aspdotnet_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blacklist_16 {
            get {
                object obj = ResourceManager.GetObject("blacklist_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blacklist_48 {
            get {
                object obj = ResourceManager.GetObject("blacklist_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blacklist_add_48 {
            get {
                object obj = ResourceManager.GetObject("blacklist_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blacklist_edit_48 {
            get {
                object obj = ResourceManager.GetObject("blacklist_edit_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///	&lt;tr&gt;
        ///
        ///		&lt;td class=&quot;header&quot;&gt;
        ///			&lt;label class=&quot;link&quot; id=&quot;lnk_ip_sorting_by_ip&quot; title=&quot;Click to sort by IP Address&quot;&gt;
        ///				IP Address
        ///			&lt;/label&gt;
        ///			&lt;img class=&quot;sorting&quot; width=&quot;10&quot; height=&quot;10&quot; alt=&quot;Sorting by IP Address&quot;
        ///				 src=&quot;&quot; id=&quot;ip_sorting_by_ip&quot; style=&quot;display:none&quot;&gt;
        ///		&lt;/td&gt;
        ///
        ///		&lt;td class=&quot;header&quot;&gt;
        ///			&lt;label class=&quot;link&quot; id=&quot;lnk_ip_sorting_by_block_date&quot; title=&quot;Click to sort by Block Date&quot;&gt;
        ///				Block Date
        ///			&lt;/label&gt;
        ///			&lt;img class=&quot;sorting&quot; width=&quot;10&quot; height=&quot;10&quot; alt=&quot;Sorting by Block Date&quot;
        ///				 src=&quot;&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string BlockedIpsTableHeader {
            get {
                return ResourceManager.GetString("BlockedIpsTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_24 {
            get {
                object obj = ResourceManager.GetObject("button_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_16_disabled {
            get {
                object obj = ResourceManager.GetObject("calendar_16_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_16_enabled {
            get {
                object obj = ResourceManager.GetObject("calendar_16_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendar_16_hot {
            get {
                object obj = ResourceManager.GetObject("calendar_16_hot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancel_16_pale {
            get {
                object obj = ResourceManager.GetObject("cancel_16_pale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancl_16 {
            get {
                object obj = ResourceManager.GetObject("cancl_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cb_arrow_disabled {
            get {
                object obj = ResourceManager.GetObject("cb_arrow_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cb_arrow_enabled {
            get {
                object obj = ResourceManager.GetObject("cb_arrow_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cb_arrow_hot {
            get {
                object obj = ResourceManager.GetObject("cb_arrow_hot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkbox_dark_disabled_checked {
            get {
                object obj = ResourceManager.GetObject("checkbox_dark_disabled_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkbox_dark_disabled_unchecked {
            get {
                object obj = ResourceManager.GetObject("checkbox_dark_disabled_unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkbox_dark_enabled_checked {
            get {
                object obj = ResourceManager.GetObject("checkbox_dark_enabled_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkbox_dark_enabled_unchecked {
            get {
                object obj = ResourceManager.GetObject("checkbox_dark_enabled_unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_16 {
            get {
                object obj = ResourceManager.GetObject("close_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloud_24 {
            get {
                object obj = ResourceManager.GetObject("cloud_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloud_24_dark {
            get {
                object obj = ResourceManager.GetObject("cloud_24_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на * {
        ///	font-family: Tahoma, Geneva, Verdana, sans-serif;
        ///	font-size: 13px;
        ///}
        ///
        ///body {
        ///	margin: 10px;
        ///}
        ///
        ///.bhr {
        ///    border-bottom: solid 1px #999;
        ///    padding-bottom: 7px;
        ///    margin-bottom: 15px;
        ///}.
        /// </summary>
        internal static string Common_Style {
            get {
                return ResourceManager.GetString("Common_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на body {
        ///	background-color: #1e1e1e;
        ///	color: #d0d0d0;
        ///
        ///	/* scrollbar colors are taken from the system scroll */
        ///	scrollbar-face-color: #4D4D4D;
        ///	scrollbar-highlight-color: #171717;
        ///	scrollbar-arrow-color: #676767;
        ///	scrollbar-base-color: #171717;
        ///}
        ///
        ///a:link{
        ///	text-decoration:none;
        ///	color:#03a1fc;
        ///}
        ///a:visited{
        ///	text-decoration:none;
        ///	color:#03a1fc;
        ///}
        ///a:hover{
        ///	color:#f90;
        ///	border-width:0;
        ///}.
        /// </summary>
        internal static string Common_Style_Dark {
            get {
                return ResourceManager.GetString("Common_Style_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на a:link{
        ///	text-decoration:none;
        ///	color:#2687c8;
        ///}
        ///a:visited{
        ///	text-decoration:none;
        ///	color:#2687c8;
        ///}
        ///a:hover{
        ///	color:#f90;
        ///	border-width:0;
        ///}.
        /// </summary>
        internal static string Common_Style_Light {
            get {
                return ResourceManager.GetString("Common_Style_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap confg_16 {
            get {
                object obj = ResourceManager.GetObject("confg_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap confg_24 {
            get {
                object obj = ResourceManager.GetObject("confg_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap config_10_v1 {
            get {
                object obj = ResourceManager.GetObject("config_10_v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap config_10_v2 {
            get {
                object obj = ResourceManager.GetObject("config_10_v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap contactus_16 {
            get {
                object obj = ResourceManager.GetObject("contactus_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_16 {
            get {
                object obj = ResourceManager.GetObject("copy_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_16_disabled {
            get {
                object obj = ResourceManager.GetObject("copy_16_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_16_disabled_dark {
            get {
                object obj = ResourceManager.GetObject("copy_16_disabled_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_16_gray {
            get {
                object obj = ResourceManager.GetObject("copy_16_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_16_inactive {
            get {
                object obj = ResourceManager.GetObject("copy_16_inactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		/*CSS*/
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///
        ///	&lt;div class=&quot;bhr&quot;&gt;
        ///		&lt;b&gt;RdpGuard Dashboard&lt;/b&gt;
        ///	&lt;/div&gt;
        ///
        ///	&lt;div class=&quot;padl_10&quot;&gt;
        ///
        ///		&lt;span class=&quot;status_lbl&quot;&gt;
        ///			RdpGuard Service:
        ///		&lt;/span&gt;
        ///
        ///		&lt;span id=&quot;service_status_pic&quot;&gt;&amp;nbsp;&lt;/span&gt;
        ///
        ///		&lt;label id=&quot;service_status&quot;&gt;Connecting..&lt;/label&gt;
        ///
        ///		&lt;span id=&quot;protection_status_enabled&quot; style=&quot;display:none;&quot;&gt;
        ///			(Protection is enabled)
        ///		&lt;/span&gt;
        ///
        ///		&lt;span id=&quot;protection_status_disabled&quot; cl [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string DashboardDialog {
            get {
                return ResourceManager.GetString("DashboardDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///	&lt;tr&gt;
        ///
        ///		&lt;td class=&quot;header&quot;&gt;
        ///			&lt;label class=&quot;link&quot; id=&quot;lnk_ip_sorting_by_ip&quot; title=&quot;Click to sort by IP Address&quot;&gt;
        ///				IP Address
        ///			&lt;/label&gt;
        ///			&lt;img class=&quot;sorting&quot; width=&quot;10&quot; height=&quot;10&quot; alt=&quot;Sorting by IP Address&quot;
        ///				 src=&quot;&quot; id=&quot;ip_sorting_by_ip&quot; style=&quot;display:none&quot;&gt;
        ///		&lt;/td&gt;
        ///
        ///		&lt;td class=&quot;header&quot;&gt;
        ///			&lt;label class=&quot;link&quot; id=&quot;lnk_ip_sorting_by_block_date&quot; title=&quot;Click to sort by Block Date&quot;&gt;
        ///				Block Date
        ///			&lt;/label&gt;
        ///			&lt;img class=&quot;sorting&quot; width=&quot;10&quot; height=&quot;10&quot; alt=&quot;Sorting by Block Date&quot;
        ///				 src=&quot;&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string DashboardDialog_IPTableHeader {
            get {
                return ResourceManager.GetString("DashboardDialog_IPTableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///
        ///    img {
        ///        border: 0px;
        ///        vertical-align: middle;
        ///        padding: 0px;
        ///        margin: 0px;
        ///    }
        ///		
        ///	.red{color:#ee0000;}
        ///	.blue{color:#0000ee;}
        ///
        ///	#blocked_ips_table {
        ///		border-collapse: collapse;
        ///		width: 100%;
        ///	}
        ///
        ///	#blocked_ips_table td {
        ///		border: 1px solid #778899;
        ///		padding: 7px;
        ///		text-align: left;
        ///	}
        ///		
        ///	.padl_10{padding:0px;margin:10px;margin-top:20px;}
        ///	.status_lbl{width:175px;}
        ///
        ///	.yellow_box,
        ///	.blue_box{
        ///		padding: 10px;
        ///		border: 1px #aaa solid;
        ///		text-align: center;
        ///		width: 100 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string DashboardDialog_Style {
            get {
                return ResourceManager.GetString("DashboardDialog_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///	body {
        ///		background-color: #1e1e1e;
        ///		color: #d0d0d0;
        ///
        ///		/* scrollbar colors are taken from the system scroll */
        ///		scrollbar-face-color: #4D4D4D;
        ///		scrollbar-highlight-color: #171717;
        ///		scrollbar-arrow-color: #676767;
        ///		scrollbar-base-color: #171717;
        ///	}
        ///
        ///	#blocked_ips_table .header {
        ///		background: #1e1e1e;
        ///	}
        ///
        ///	.yellow_box {
        ///		background-color: #222;
        ///		color: #ff0;
        ///		border-color: #ffff99;
        ///	}
        ///	.yellow_box a:hover {
        ///		color: red !important;
        ///	}
        ///
        ///	.blue_box {
        ///		color: #78cbf5;
        ///	}
        ///
        ///	a.switcher {
        ///		color: #d0d [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string DashboardDialog_Style_Dark {
            get {
                return ResourceManager.GetString("DashboardDialog_Style_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 	#blocked_ips_table .header {
        ///		background: #ddd;
        ///	}
        ///
        ///	.yellow_box {
        ///		background-color: #ffff99;
        ///	}
        ///	.yellow_box a:hover{
        ///		color:#f00;
        ///	}
        ///
        ///	.blue_box {
        ///		background-color: aliceblue;
        ///	}
        ///
        ///	a.switcher {
        ///		color: #000 !important;
        ///		background-color: #fff;
        ///		border: solid 1px #fff;
        ///	}
        ///
        ///	a.active_switcher,
        ///	a.switcher:hover {
        ///		color: #000 !important;
        ///		background-color: #ddd;
        ///		border: solid 1px #778899;
        ///	}
        ///
        ///	a.ip_lnk_visited {
        ///		color: #551A8B;
        ///	}.
        /// </summary>
        internal static string DashboardDialog_Style_Light {
            get {
                return ResourceManager.GetString("DashboardDialog_Style_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap debug_48 {
            get {
                object obj = ResourceManager.GetObject("debug_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap del_10 {
            get {
                object obj = ResourceManager.GetObject("del_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap del_16 {
            get {
                object obj = ResourceManager.GetObject("del_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_16_pale {
            get {
                object obj = ResourceManager.GetObject("delete_16_pale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diagnostics_16 {
            get {
                object obj = ResourceManager.GetObject("diagnostics_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap diagnostics_48 {
            get {
                object obj = ResourceManager.GetObject("diagnostics_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;!doctype html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta charset=&quot;utf-8&quot; /&gt;
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///		/*DLG_CSS*/
        ///	&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///
        ///	&lt;div class=&quot;bhr&quot;&gt;
        ///		&lt;div class=&quot;dlg_header_row&quot;&gt;
        ///			&lt;div class=&quot;dlg_header_left&quot;&gt;
        ///				&lt;span class=&quot;dlg_icon&quot;&gt;
        ///					&lt;!--DLG_ICON--&gt;
        ///				&lt;/span&gt;
        ///				&lt;div class=&quot;dlg_titles&quot;&gt;
        ///					&lt;div class=&quot;dlg_main_title&quot; id=&quot;dlg_main_title&quot;&gt;
        ///						&lt;!--DLG_TITLE--&gt;
        ///					&lt;/div&gt;
        ///					&lt;div class=&quot;dlg_sub_title&quot; id=&quot;dlg_sub_title&quot;&gt;
        ///						&lt;!--DLG_SUBTITLE--&gt;
        ///					&lt;/div&gt;
        ///				&lt;/div&gt;
        ///			&lt;/div&gt;
        ///			&lt;div  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Dlg_Cmn {
            get {
                return ResourceManager.GetString("Dlg_Cmn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на html, body {
        ///	height: 100%;
        ///}
        ///
        ///body {
        ///	display: flex;
        ///	flex-direction: column;
        ///	overflow: hidden;
        ///}
        ///
        ///input[type=number],
        ///input[type=text],
        ///textarea {
        ///	border: 1px solid #3a3a3a;
        ///}
        ///
        ///input[type=number]:focus,
        ///input[type=number]:hover,
        ///input[type=text]:focus,
        ///input[type=text]:hover,
        ///textarea:focus,
        ///textarea:hover{
        ///	outline: none;
        ///	border-color: #5b9bd5;
        ///	box-shadow: 0 0 0 1px rgba(3,161,252,.15);
        ///}
        ///
        ///input[type=checkbox]:focus-visible {
        ///	outline: 1px solid #5b9bd5;
        ///	outline-offset: 3px;
        ///	box-shadow: 0 0 0 1px r [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Dlg_Cmn_Style {
            get {
                return ResourceManager.GetString("Dlg_Cmn_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .panels,
        ///.panel,
        ///input,
        ///select,
        ///textarea {
        ///	color-scheme: dark;
        ///}
        ///
        ///input[type=number],
        ///input[type=text],
        ///textarea {
        ///	background-color: #2a2a2a;
        ///	color: #e6e6e6;
        ///}
        ///
        ///input::placeholder,
        ///textarea::placeholder {
        ///	color: #9a9a9a;
        ///	opacity: 1;
        ///}
        ///
        ///input[type=checkbox] {
        ///	accent-color: #03a1fc;
        ///}
        ///
        ///.tab {
        ///	color: #7a7a7a;
        ///	border-color: #3a3a3a;
        ///	background: #292929;
        ///}
        ///
        ///.tab:hover {
        ///	background: #353535;
        ///	color: #bbb;
        ///}
        ///
        ///.tab.is-active { 
        ///	color: #fff; 
        ///	background: #212121;
        ///}
        ///
        ///.panels {
        ///	background: #212121; 
        ///	bord [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Dlg_Cmn_Style_Dark {
            get {
                return ResourceManager.GetString("Dlg_Cmn_Style_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .panels,
        ///.panel,
        ///input,
        ///select,
        ///textarea {
        ///	color-scheme: light;
        ///}
        ///
        ///body {
        ///	background: #f7f7f7;
        ///}
        ///
        ///.tab {
        ///	color: #000000;
        ///	border-color: #c9c9c9;
        ///}
        ///
        ///.tab:hover {
        ///	background: #f7f7f7;
        ///	color: #000000;
        ///}
        ///
        ///.tab.is-active {
        ///	background: #ffffff;
        ///}
        ///
        ///.panels {
        ///	background: #ffffff;
        ///	border-color: #c9c9c9;
        ///}
        ///
        ///.footer_bar {
        ///	border-top-color: #c9c9c9;
        ///	background: #f7f7f7;
        ///}
        ///
        ///.btn_ok {
        ///	border-color: #2e7d32;
        ///	color: #2e7d32;
        ///}
        ///
        ///.btn_ok:hover {
        ///	background: rgba(46,125,50,.12);
        ///}
        ///
        ///.btn_cancel {
        ///	border-color: #b [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Dlg_Cmn_Style_Light {
            get {
                return ResourceManager.GetString("Dlg_Cmn_Style_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap docs_24 {
            get {
                object obj = ResourceManager.GetObject("docs_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down_10 {
            get {
                object obj = ResourceManager.GetObject("down_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down_16_pale {
            get {
                object obj = ResourceManager.GetObject("down_16_pale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_10 {
            get {
                object obj = ResourceManager.GetObject("edit_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_16 {
            get {
                object obj = ResourceManager.GetObject("edit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit_16_pale {
            get {
                object obj = ResourceManager.GetObject("edit_16_pale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap environment_24 {
            get {
                object obj = ResourceManager.GetObject("environment_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap error_16 {
            get {
                object obj = ResourceManager.GetObject("error_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit_16 {
            get {
                object obj = ResourceManager.GetObject("exit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fastf_16 {
            get {
                object obj = ResourceManager.GetObject("fastf_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap filter_48 {
            get {
                object obj = ResourceManager.GetObject("filter_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap firewall_edit_48 {
            get {
                object obj = ResourceManager.GetObject("firewall_edit_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_16_gray {
            get {
                object obj = ResourceManager.GetObject("folder_16_gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_add_16 {
            get {
                object obj = ResourceManager.GetObject("folder_add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_delete_16 {
            get {
                object obj = ResourceManager.GetObject("folder_delete_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_edit_16 {
            get {
                object obj = ResourceManager.GetObject("folder_edit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder16 {
            get {
                object obj = ResourceManager.GetObject("folder16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foldr_16_aqua {
            get {
                object obj = ResourceManager.GetObject("foldr_16_aqua", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///
        ///&lt;head&gt;
        ///	&lt;title&gt;&lt;/title&gt;
        ///	
        ///	&lt;style type=&quot;text/css&quot;&gt;
        ///
        ///        * {
        ///            font-family: Arial,Helvetica,Sans-Serif;
        ///            font-size: 13px;
        ///        }
        ///
        ///        body {
        ///            border: 1px solid #999;
        ///            margin: 10px
        ///        }
        ///
        ///        img {
        ///            border: 0px;
        ///            vertical-align: middle;
        ///            padding: 0px;
        ///            margin: 0px;
        ///        }
        ///
        ///        .bhr {
        ///            border-bottom: solid 1px #999;
        ///            padding-bottom: [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string formMain {
            get {
                return ResourceManager.GetString("formMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ftp_48 {
            get {
                object obj = ResourceManager.GetObject("ftp_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap get_pro {
            get {
                object obj = ResourceManager.GetObject("get_pro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gray_ball {
            get {
                object obj = ResourceManager.GetObject("gray_ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_ball {
            get {
                object obj = ResourceManager.GetObject("green_ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hd_16 {
            get {
                object obj = ResourceManager.GetObject("hd_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap http_48 {
            get {
                object obj = ResourceManager.GetObject("http_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imap_48 {
            get {
                object obj = ResourceManager.GetObject("imap_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap informaion_16 {
            get {
                object obj = ResourceManager.GetObject("informaion_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key_16 {
            get {
                object obj = ResourceManager.GetObject("key_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list_16 {
            get {
                object obj = ResourceManager.GetObject("list_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loading_16 {
            get {
                object obj = ResourceManager.GetObject("loading_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap location_pin_16 {
            get {
                object obj = ResourceManager.GetObject("location_pin_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap location_pin_16_dark {
            get {
                object obj = ResourceManager.GetObject("location_pin_16_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap location_pin_24 {
            get {
                object obj = ResourceManager.GetObject("location_pin_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap location_pin_24_dark {
            get {
                object obj = ResourceManager.GetObject("location_pin_24_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap location_pin_48 {
            get {
                object obj = ResourceManager.GetObject("location_pin_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap location_pin_48_dark {
            get {
                object obj = ResourceManager.GetObject("location_pin_48_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap location_pin_settings_48 {
            get {
                object obj = ResourceManager.GetObject("location_pin_settings_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap location_pin_settings_48_dark {
            get {
                object obj = ResourceManager.GetObject("location_pin_settings_48_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magnifier_10 {
            get {
                object obj = ResourceManager.GetObject("magnifier_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap magnifier_16 {
            get {
                object obj = ResourceManager.GetObject("magnifier_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mail_server_48 {
            get {
                object obj = ResourceManager.GetObject("mail_server_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mail_server_add_48 {
            get {
                object obj = ResourceManager.GetObject("mail_server_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mail_server_edit_48 {
            get {
                object obj = ResourceManager.GetObject("mail_server_edit_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap more_16 {
            get {
                object obj = ResourceManager.GetObject("more_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ms_sql_48 {
            get {
                object obj = ResourceManager.GetObject("ms_sql_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ms_sql_filter_48 {
            get {
                object obj = ResourceManager.GetObject("ms_sql_filter_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mysql_logo_48 {
            get {
                object obj = ResourceManager.GetObject("mysql_logo_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_version_check_24 {
            get {
                object obj = ResourceManager.GetObject("new_version_check_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notifications_16 {
            get {
                object obj = ResourceManager.GetObject("notifications_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notifications_48 {
            get {
                object obj = ResourceManager.GetObject("notifications_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notifications_add_48 {
            get {
                object obj = ResourceManager.GetObject("notifications_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notifications_edit_48 {
            get {
                object obj = ResourceManager.GetObject("notifications_edit_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap num_down_disabled {
            get {
                object obj = ResourceManager.GetObject("num_down_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap num_down_disabled_light {
            get {
                object obj = ResourceManager.GetObject("num_down_disabled_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap num_down_enabled {
            get {
                object obj = ResourceManager.GetObject("num_down_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap num_down_enabled_light {
            get {
                object obj = ResourceManager.GetObject("num_down_enabled_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap num_down_hot {
            get {
                object obj = ResourceManager.GetObject("num_down_hot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap num_down_hot_light {
            get {
                object obj = ResourceManager.GetObject("num_down_hot_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap num_up_disabled {
            get {
                object obj = ResourceManager.GetObject("num_up_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap num_up_disabled_light {
            get {
                object obj = ResourceManager.GetObject("num_up_disabled_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap num_up_enabled {
            get {
                object obj = ResourceManager.GetObject("num_up_enabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap num_up_enabled_light {
            get {
                object obj = ResourceManager.GetObject("num_up_enabled_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap num_up_hot {
            get {
                object obj = ResourceManager.GetObject("num_up_hot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap num_up_hot_light {
            get {
                object obj = ResourceManager.GetObject("num_up_hot_light", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ok_16_pale {
            get {
                object obj = ResourceManager.GetObject("ok_16_pale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap online_help_24 {
            get {
                object obj = ResourceManager.GetObject("online_help_24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open_16 {
            get {
                object obj = ResourceManager.GetObject("open_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;div class=&quot;tabs&quot; id=&quot;tabs&quot;&gt;
        ///	&lt;button class=&quot;tab is-active&quot; data-tab=&quot;general&quot;&gt;General&lt;/button&gt;
        ///	&lt;button class=&quot;tab&quot; data-tab=&quot;ipcloud&quot;&gt;IP Cloud&lt;/button&gt;
        ///	&lt;button class=&quot;tab&quot; data-tab=&quot;geoip&quot;&gt;GeoIP&lt;/button&gt;
        ///	&lt;button class=&quot;tab&quot; data-tab=&quot;interface&quot;&gt;Interface&lt;/button&gt;
        ///	&lt;button class=&quot;tab&quot; data-tab=&quot;connection&quot;&gt;Connection&lt;/button&gt;
        ///	&lt;button class=&quot;tab&quot; data-tab=&quot;logging&quot;&gt;Logging&lt;/button&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;div class=&quot;panels&quot;&gt;
        ///
        ///	&lt;div class=&quot;panel&quot; data-tab=&quot;general&quot; style=&quot;display:block;&quot;&gt;
        ///
        ///		&lt;label class=&quot;chk_row&quot;&gt;
        ///			&lt; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string OptionsDialogV2 {
            get {
                return ResourceManager.GetString("OptionsDialogV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;svg version=&quot;1.1&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot; style=&quot;display: block;&quot; viewBox=&quot;0 0 2048 2048&quot; width=&quot;512&quot; height=&quot;512&quot; preserveAspectRatio=&quot;none&quot;&gt;
        ///&lt;defs&gt;
        ///	&lt;linearGradient id=&quot;Gradient1&quot; gradientUnits=&quot;userSpaceOnUse&quot; x1=&quot;494.946&quot; y1=&quot;1268.83&quot; x2=&quot;499.03&quot; y2=&quot;1622.08&quot;&gt;
        ///		&lt;stop class=&quot;stop0&quot; offset=&quot;0&quot; stop-opacity=&quot;1&quot; stop-color=&quot;rgb(79,108,193)&quot;/&gt;
        ///		&lt;stop class=&quot;stop1&quot; offset=&quot;1&quot; stop-opacity=&quot;1&quot; stop-color=&quot;rgb(23,172,219)&quot;/&gt;
        ///	&lt;/linearGradient&gt;
        ///	&lt;linearGradient id=&quot;Gradient2&quot; gradientUnits=&quot;userSpa [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string OptionsDialogV2_Main_Icon {
            get {
                return ResourceManager.GetString("OptionsDialogV2_Main_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на addEvt(&apos;lnk_advanced&apos;, &apos;click&apos;, &apos;advanced&apos;);
        ///addEvt(document, &apos;dblclick&apos;, &apos;dblclick&apos;);.
        /// </summary>
        internal static string OptionsDialogV2_Script {
            get {
                return ResourceManager.GetString("OptionsDialogV2_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap opts_16 {
            get {
                object obj = ResourceManager.GetObject("opts_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap phone_receiver_48 {
            get {
                object obj = ResourceManager.GetObject("phone_receiver_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_16 {
            get {
                object obj = ResourceManager.GetObject("play_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus_10 {
            get {
                object obj = ResourceManager.GetObject("plus_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pop3_48 {
            get {
                object obj = ResourceManager.GetObject("pop3_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap question_16 {
            get {
                object obj = ResourceManager.GetObject("question_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radio_dark_disabled_checked {
            get {
                object obj = ResourceManager.GetObject("radio_dark_disabled_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radio_dark_disabled_unchecked {
            get {
                object obj = ResourceManager.GetObject("radio_dark_disabled_unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radio_dark_enabled_checked {
            get {
                object obj = ResourceManager.GetObject("radio_dark_enabled_checked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap radio_dark_enabled_unchecked {
            get {
                object obj = ResourceManager.GetObject("radio_dark_enabled_unchecked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rdp_48 {
            get {
                object obj = ResourceManager.GetObject("rdp_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon rdpguard_16x16_icon {
            get {
                object obj = ResourceManager.GetObject("rdpguard_16x16_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rdpguard_logo_128 {
            get {
                object obj = ResourceManager.GetObject("rdpguard_logo_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rdweb_48 {
            get {
                object obj = ResourceManager.GetObject("rdweb_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap red_ball {
            get {
                object obj = ResourceManager.GetObject("red_ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redo_16 {
            get {
                object obj = ResourceManager.GetObject("redo_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ref_16 {
            get {
                object obj = ResourceManager.GetObject("ref_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap regedit_16 {
            get {
                object obj = ResourceManager.GetObject("regedit_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_16 {
            get {
                object obj = ResourceManager.GetObject("save_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_16_blue {
            get {
                object obj = ResourceManager.GetObject("save_16_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap select_all {
            get {
                object obj = ResourceManager.GetObject("select_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smtp_48 {
            get {
                object obj = ResourceManager.GetObject("smtp_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_ascending {
            get {
                object obj = ResourceManager.GetObject("sort_ascending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sort_descending {
            get {
                object obj = ResourceManager.GetObject("sort_descending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap splay_16 {
            get {
                object obj = ResourceManager.GetObject("splay_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap telephone_48 {
            get {
                object obj = ResourceManager.GetObject("telephone_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap traffic_monitoring_48 {
            get {
                object obj = ResourceManager.GetObject("traffic_monitoring_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trash_16 {
            get {
                object obj = ResourceManager.GetObject("trash_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unblock_16 {
            get {
                object obj = ResourceManager.GetObject("unblock_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unblock_all_16 {
            get {
                object obj = ResourceManager.GetObject("unblock_all_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up_10 {
            get {
                object obj = ResourceManager.GetObject("up_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up_16_pale {
            get {
                object obj = ResourceManager.GetObject("up_16_pale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wait {
            get {
                object obj = ResourceManager.GetObject("wait", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wait_16 {
            get {
                object obj = ResourceManager.GetObject("wait_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wait_16_dark {
            get {
                object obj = ResourceManager.GetObject("wait_16_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wait_25 {
            get {
                object obj = ResourceManager.GetObject("wait_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wait_25_dark {
            get {
                object obj = ResourceManager.GetObject("wait_25_dark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap warning_16 {
            get {
                object obj = ResourceManager.GetObject("warning_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap whitelist_16 {
            get {
                object obj = ResourceManager.GetObject("whitelist_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap whitelist_48 {
            get {
                object obj = ResourceManager.GetObject("whitelist_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap whitelist_add_48 {
            get {
                object obj = ResourceManager.GetObject("whitelist_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap whitelist_edit_48 {
            get {
                object obj = ResourceManager.GetObject("whitelist_edit_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windows_firewall_16 {
            get {
                object obj = ResourceManager.GetObject("windows_firewall_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellow_ball {
            get {
                object obj = ResourceManager.GetObject("yellow_ball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
